apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: json-predicate-transformer
  description: A simple utility for modifying JSON objects using a predicate-transformer paradigm
  owner: unknown
spec:
  type: unknown
  lifecycle: production
  owner: unknown
  system: Clever
